CREATE TABLE Users (
    UserId INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL,
    FullName NVARCHAR(100) NOT NULL,
    Role NVARCHAR(20) NOT NULL
);

CREATE TABLE Assets (
    AssetId INT IDENTITY(1,1) PRIMARY KEY,
    AssetName NVARCHAR(100) NOT NULL,
    Category NVARCHAR(50) NOT NULL,
    SerialNumber NVARCHAR(100) NOT NULL,
    Status NVARCHAR(30) NOT NULL,
    Location NVARCHAR(100) NOT NULL
);